version: "3.9"

services:
    deliverycx_bot:
        container_name: deliverycx_bot
        build:
            context: ./bot
        depends_on:
            - mongodb
        networks:
            - mynetwork
    mongodb:
        container_name: development_mongodb
        image: mongo
        volumes:
            - ./mongo/data:/data/db   
        networks:
            - mynetwork
networks:
  mynetwork:
    external:
      name: delivglobalnetwork             